name: Feature Request
description: Whats a good idea you want in Vs Paint?
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on Vs Paint?
    validations:
      required: true
